#!/usr/bin/env python3
"""Generate expected_layernorm.h for UnitTestLayerNorm (FLOAT32, #148 PR-1).

Emits PyTorch-derived ground truth: forward output y, propLoss dx, and the
parameter grads dgamma/dbeta, for several fixtures covering D in {1, 2,
full-rank} and G>1. Uses F.layer_norm (biased variance, divide by N) and
NEVER torch.var (which defaults to ddof=1). Self-checks the forward against a
hand-derived biased-variance reference. lossGrad is randn (non-uniform) so the
dx reduction and dgamma/dbeta-over-groups paths are non-vacuous under mutation.

Run via `uv run` (CMake wires this automatically).
"""
import argparse
import sys
from pathlib import Path

import torch
import torch.nn.functional as F


def _format_float_literal(v: float) -> str:
    s = repr(v)
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit_float_array(name: str, tensor: torch.Tensor) -> str:
    flat = tensor.detach().flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def _hand_check_forward(x, normalized_shape, gamma, beta, eps):
    """Biased-variance (divide by N) reference, eps inside sqrt, two-pass."""
    D = len(normalized_shape)
    N = 1
    for s in normalized_shape:
        N *= s
    G = x.numel() // N
    xr = x.reshape(G, N)
    mean = xr.mean(dim=1, keepdim=True)
    var = ((xr - mean) ** 2).mean(dim=1, keepdim=True)  # biased, ddof=0
    nhat = (xr - mean) / torch.sqrt(var + eps)
    y = nhat * gamma.reshape(1, N) + beta.reshape(1, N)
    return y.reshape(x.shape)


def _run_fixture(name, x, normalized_shape, *, eps=1e-5, seed=0):
    torch.manual_seed(seed)
    gamma = torch.randn(normalized_shape, dtype=torch.float64)
    beta = torch.randn(normalized_shape, dtype=torch.float64)

    x_in = x.clone().detach().to(torch.float64).requires_grad_(True)
    g_in = gamma.clone().detach().requires_grad_(True)
    b_in = beta.clone().detach().requires_grad_(True)

    y = F.layer_norm(x_in, normalized_shape, weight=g_in, bias=b_in, eps=eps)

    expected_y = _hand_check_forward(x_in.detach(), normalized_shape,
                                     g_in.detach(), b_in.detach(), eps)
    assert torch.allclose(y.detach(), expected_y, atol=1e-9), (
        f"{name}: F.layer_norm disagrees with biased-variance hand-derived"
    )

    gy = torch.randn_like(y)
    y.backward(gy)

    return {
        "name": name,
        "x": x_in.detach().to(torch.float32),
        "gamma": g_in.detach().to(torch.float32),
        "beta": b_in.detach().to(torch.float32),
        "y": y.detach().to(torch.float32),
        "dx": x_in.grad.detach().to(torch.float32),
        "dgamma": g_in.grad.detach().to(torch.float32),
        "dbeta": b_in.grad.detach().to(torch.float32),
        "gy": gy.detach().to(torch.float32),
        "normalized_shape": normalized_shape,
    }


def fixture_d1_single_group():
    # rank-1 [5], normalized_shape=[5] -> D=1, G=1.
    x = torch.tensor([1.5, -2.0, 0.5, 3.0, -1.0])
    return _run_fixture("d1SingleGroup", x, [5], seed=11)


def fixture_d1_multi_group():
    # rank-2 [3,4], normalized_shape=[4] -> D=1, G=3 (catches dgamma/dbeta sum).
    torch.manual_seed(12)
    x = torch.randn(3, 4)
    return _run_fixture("d1MultiGroup", x, [4], seed=13)


def fixture_d2_multi_group():
    # rank-3 [2,3,4], normalized_shape=[3,4] -> D=2, N=12, G=2.
    torch.manual_seed(14)
    x = torch.randn(2, 3, 4)
    return _run_fixture("d2MultiGroup", x, [3, 4], seed=15)


def fixture_full_rank():
    # rank-2 [2,3], normalized_shape=[2,3] -> D=full, G=1.
    torch.manual_seed(16)
    x = torch.randn(2, 3)
    return _run_fixture("fullRank", x, [2, 3], seed=17)


def emit_fixture(parts, fx):
    pre = f"layerNorm_{fx['name']}"
    parts.append(emit_float_array(f"input_{pre}", fx["x"]))
    parts.append(emit_float_array(f"gamma_{pre}", fx["gamma"]))
    parts.append(emit_float_array(f"beta_{pre}", fx["beta"]))
    parts.append(emit_float_array(f"expectedForward_{pre}", fx["y"]))
    parts.append(emit_float_array(f"lossGrad_{pre}", fx["gy"]))
    parts.append(emit_float_array(f"expectedPropLoss_{pre}", fx["dx"]))
    parts.append(emit_float_array(f"expectedDgamma_{pre}", fx["dgamma"]))
    parts.append(emit_float_array(f"expectedDbeta_{pre}", fx["dbeta"]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_layernorm.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_LAYERNORM_H\n",
        "#define ODT_EXPECTED_LAYERNORM_H\n",
        "#include <stdlib.h>\n\n",
    ]

    fixtures = [
        fixture_d1_single_group(),
        fixture_d1_multi_group(),
        fixture_d2_multi_group(),
        fixture_full_rank(),
    ]
    for fx in fixtures:
        emit_fixture(parts, fx)

    parts.append("\n#endif // ODT_EXPECTED_LAYERNORM_H\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
