#!/usr/bin/env python3
"""Generate expected_conv_transpose_1d_kernel.h.

Produces a C header with PyTorch-derived ground-truth output values for
each ConvTranspose1dKernel test fixture, plus an autograd-derived
adjoint fixture that protects PR 2's Conv1d backward path.

Run via ``uv run`` (CMake wires this automatically).
"""
import argparse
import math
import sys
from pathlib import Path

import torch
import torch.nn.functional as F


def _format_float_literal(v: float) -> str:
    """Format a Python float as a valid C float literal.

    The naive ``f"{v:.9g}f"`` produces things like ``10f`` for
    whole-number floats, which gcc rejects as 'invalid suffix "f" on
    integer constant'. Python's ``repr`` always emits a decimal point
    or exponent for finite floats (since Python 3.1), so
    ``repr(v) + "f"`` is always valid C.
    """
    if not math.isfinite(v):
        raise ValueError(f"non-finite float in fixture: {v!r}")
    return repr(v) + "f"


def emit_float_array(name: str, tensor: torch.Tensor) -> str:
    flat = tensor.detach().flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def fixture_basic():
    # B=1, Cin=1, Cout=1, L=3, K=2; output L=4
    x = torch.tensor([[[1.0, 2.0, 3.0]]])
    w = torch.tensor([[[2.0, 4.0]]])
    y = F.conv_transpose1d(x, w, bias=None, stride=1, padding=0,
                           output_padding=0, dilation=1, groups=1)
    return ("basic", y)


def fixture_with_stride():
    # B=1, Cin=1, Cout=1, L=3, K=2, stride=2; output L=6
    # Lout = (L-1)*stride - 2*padding + dilation*(K-1) + output_padding + 1
    #      = 2*2 - 0 + 1 + 0 + 1 = 6
    x = torch.tensor([[[1.0, 2.0, 3.0]]])
    w = torch.tensor([[[2.0, 4.0]]])
    y = F.conv_transpose1d(x, w, bias=None, stride=2, padding=0,
                           output_padding=0, dilation=1, groups=1)
    return ("withStride", y)


def fixture_with_output_padding():
    # Same as with_stride but output_padding=1; Lout=7
    x = torch.tensor([[[1.0, 2.0, 3.0]]])
    w = torch.tensor([[[2.0, 4.0]]])
    y = F.conv_transpose1d(x, w, bias=None, stride=2, padding=0,
                           output_padding=1, dilation=1, groups=1)
    return ("withOutputPadding", y)


def fixture_groups():
    # B=1, Cin=4, Cout=4, K=2, groups=2 (so Cout/groups=2)
    torch.manual_seed(7)
    x = torch.randn(1, 4, 3)
    w = torch.randn(4, 2, 2)  # [Cin=4, Cout/groups=2, K=2]
    y = F.conv_transpose1d(x, w, bias=None, stride=1, padding=0,
                           output_padding=0, dilation=1, groups=2)
    return ("groups", y, x, w)


def fixture_adjoint_same_grouped():
    """Adjoint of Conv1d(K=3, stride=1, dilation=1, SAME, groups=2) on B=2 Cin=4.

    The adjoint is computed as: dL/dx of conv1d w.r.t. random lossGrad.
    Returns lossGrad as 'input', conv1d-W as 'weight', expected dL/dx as 'expected'.
    """
    torch.manual_seed(50)
    x_dummy = torch.zeros(2, 4, 6, requires_grad=True)
    w = torch.randn(4, 2, 3)  # Conv1d weight: [Cout=4, Cin/g=2, K=3]
    y = F.conv1d(x_dummy, w, bias=None, stride=1, padding=1, dilation=1, groups=2)
    # gy is the lossGrad; pick a non-trivial pattern (random) so the test
    # is sensitive to indexing bugs. Note: y.shape == [2, 4, 6] for this config.
    gy = torch.randn_like(y)
    y.backward(gy)
    # ConvT-Kernel input is the forward conv1d's lossGrad (gy). Its weight is
    # Conv1d's weight (same memory). Its output (= propLoss) is x_dummy.grad.
    return ("adjointSameGrouped", gy.detach(), w, x_dummy.grad.detach())


def fixture_adjoint_check():
    # Setup: a tiny Conv1d, compute dL/dx by autograd, then ensure
    # convTranspose1d(grad_output, W) reproduces it.
    torch.manual_seed(11)
    x = torch.randn(1, 2, 5, requires_grad=True)
    w = torch.randn(3, 2, 3, requires_grad=False)
    y = F.conv1d(x, w, bias=None, stride=1, padding=0, dilation=1, groups=1)
    grad_y = torch.randn_like(y)
    y.backward(grad_y)
    grad_x_autograd = x.grad.clone()
    # Now do the same via conv_transpose1d (manual) — should equal autograd
    grad_x_via_transpose = F.conv_transpose1d(
            grad_y, w, bias=None, stride=1, padding=0,
            output_padding=0, dilation=1, groups=1)
    assert torch.allclose(grad_x_autograd, grad_x_via_transpose, atol=1e-5), (
            "PyTorch self-consistency check failed: "
            "F.conv_transpose1d(grad_y, W) should equal autograd dL/dx")
    return ("adjointCheck", grad_x_autograd, grad_y, w, x.detach())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_conv_transpose_1d_kernel.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_CONV_TRANSPOSE_1D_KERNEL_H\n",
        "#define ODT_EXPECTED_CONV_TRANSPOSE_1D_KERNEL_H\n",
        "#include <stdlib.h>\n\n",
    ]

    fixtures_simple = [
        fixture_basic(),
        fixture_with_stride(),
        fixture_with_output_padding(),
    ]
    for name, y in fixtures_simple:
        parts.append(emit_float_array(f"expectedConvT1dForward_{name}", y))

    name, y, x, w = fixture_groups()
    parts.append(emit_float_array(f"expectedConvT1dForward_{name}", y))
    parts.append(emit_float_array(f"inputConvT1dForward_{name}", x))
    parts.append(emit_float_array(f"weightConvT1dForward_{name}", w))

    name, gx, gy, ww, xx = fixture_adjoint_check()
    parts.append(emit_float_array(f"expectedConvT1dForward_{name}", gx))
    parts.append(emit_float_array(f"inputConvT1dForward_{name}", gy))
    parts.append(emit_float_array(f"weightConvT1dForward_{name}", ww))

    name, gy_sg, w_sg, exp_sg = fixture_adjoint_same_grouped()
    parts.append(emit_float_array(f"inputConvT1d_{name}", gy_sg))
    parts.append(emit_float_array(f"weightConvT1d_{name}", w_sg))
    parts.append(emit_float_array(f"expectedConvT1d_{name}", exp_sg))

    parts.append("\n#endif // ODT_EXPECTED_CONV_TRANSPOSE_1D_KERNEL_H\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
