#!/usr/bin/env python3
"""Generate expected_conv1d_kernel.h for UnitTestConv1dKernel.

Produces a C header with PyTorch-derived ground-truth output values for
each test fixture. Run via `uv run` (CMake wires this automatically).
"""
import argparse
import sys
from pathlib import Path

import torch
import torch.nn.functional as F


def _format_float_literal(v: float) -> str:
    """Format a Python float as a valid C float literal.

    Python's ``f"{v:.9g}"`` strips the trailing ``.0`` from whole-number
    floats (``10.0`` → ``"10"``), which combined with the ``f`` suffix
    produces invalid C (``10f`` is rejected by gcc as an integer suffix).
    Use ``repr`` for a shortest-round-trip representation that always
    contains a decimal point or an exponent, both legal in C with ``f``.
    """
    s = repr(v)
    # repr handles inf/nan as "inf"/"nan" — guard for them anyway since
    # the C suffix would not apply.
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit_float_array(name: str, tensor: torch.Tensor) -> str:
    flat = tensor.detach().flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def fixture_single_channel_single_batch():
    # B=1, Cin=1, Cout=1, L=4, K=2, no bias
    x = torch.tensor([[[1.0, 2.0, 3.0, 4.0]]])
    w = torch.tensor([[[2.0, 4.0]]])
    y = F.conv1d(x, w, bias=None, stride=1, padding=0, dilation=1, groups=1)
    return ("singleChannelSingleBatch", y)


def fixture_multi_channel_with_bias():
    # B=1, Cin=3, Cout=2, L=5, K=3
    torch.manual_seed(0)
    x = torch.arange(15.0).reshape(1, 3, 5)
    w = torch.arange(18.0).reshape(2, 3, 3) * 0.1
    b = torch.tensor([0.5, -0.5])
    y = F.conv1d(x, w, bias=b, stride=1, padding=0, dilation=1, groups=1)
    return ("multiChannelWithBias", y)


def fixture_multi_batch():
    # B=4, Cin=2, Cout=2, L=4, K=2
    torch.manual_seed(1)
    x = torch.randn(4, 2, 4)
    w = torch.randn(2, 2, 2)
    y = F.conv1d(x, w, bias=None, stride=1, padding=0, dilation=1, groups=1)
    return ("multiBatch", y, x, w)


def fixture_groups_depthwise():
    # B=1, Cin=4, Cout=4, K=2, groups=4 (depthwise)
    torch.manual_seed(2)
    x = torch.randn(1, 4, 5)
    w = torch.randn(4, 1, 2)  # [Cout, Cin/groups=1, K]
    y = F.conv1d(x, w, bias=None, stride=1, padding=0, dilation=1, groups=4)
    return ("groupsDepthwise", y, x, w)


def fixture_groups_grouped():
    # B=1, Cin=4, Cout=8, K=2, groups=2
    torch.manual_seed(3)
    x = torch.randn(1, 4, 5)
    w = torch.randn(8, 2, 2)  # [Cout, Cin/groups=2, K]
    y = F.conv1d(x, w, bias=None, stride=1, padding=0, dilation=1, groups=2)
    return ("groupsGrouped", y, x, w)


def fixture_stride_dilation():
    # B=1, Cin=1, Cout=1, L=9, K=2, stride=3, dilation=2, no padding
    x = torch.tensor([[[1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 3.0, 0.0, 4.0]]])
    w = torch.tensor([[[2.0, 4.0]]])
    y = F.conv1d(x, w, bias=None, stride=3, padding=0, dilation=2, groups=1)
    return ("strideDilation", y)


def fixture_same_padding():
    # B=1, Cin=1, Cout=1, L=5, K=3, stride=1, dilation=1, SAME (pad=1 each side)
    x = torch.tensor([[[1.0, 2.0, 3.0, 4.0, 5.0]]])
    w = torch.tensor([[[1.0, 2.0, 3.0]]])
    # PyTorch SAME: padding=1 with K=3 stride=1 dilation=1 yields outLen=inLen
    y = F.conv1d(x, w, bias=None, stride=1, padding=1, dilation=1, groups=1)
    return ("samePadding", y)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_conv1d_kernel.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_CONV1D_KERNEL_H\n",
        "#define ODT_EXPECTED_CONV1D_KERNEL_H\n",
        "#include <stdlib.h>\n\n",
    ]

    fixtures_simple = [
        fixture_single_channel_single_batch(),
        fixture_multi_channel_with_bias(),
        fixture_stride_dilation(),
        fixture_same_padding(),
    ]
    for name, y in fixtures_simple:
        parts.append(emit_float_array(f"expectedConv1dForward_{name}", y))

    fixtures_with_inputs = [
        fixture_multi_batch(),
        fixture_groups_depthwise(),
        fixture_groups_grouped(),
    ]
    for name, y, x, w in fixtures_with_inputs:
        parts.append(emit_float_array(f"expectedConv1dForward_{name}", y))
        parts.append(emit_float_array(f"inputConv1dForward_{name}", x))
        parts.append(emit_float_array(f"weightConv1dForward_{name}", w))

    parts.append("\n#endif // ODT_EXPECTED_CONV1D_KERNEL_H\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
