"""Emit gold input/expected arrays for the PointwiseFused primitives from torch.

Fixture lengths are MULTIPLES OF 32: torch's vectorized CPU kernels are the
parity target; its scalar tail is FMA-contracted and size-dependent, so
non-multiple sizes would pin platform-dependent bits.

Self-checks: addcmul recomputes the expected values with numpy float32
separate roundings in the documented order and asserts bit-equality with
torch (catches an unexpectedly FMA-contracted torch kernel loudly at
generation time). addcdivDenom ALSO recomputes via numpy, but there the
numpy replication IS the gold source, not merely a self-check (#353): torch's
addcdiv vectorization is platform-dependent — Linux-AVX2 fuses the final
multiply-add into something like fma(s, term, self), while macOS-ARM rounds
it separately. With a~O(1) (the STANDARD fixture) that <=1-ulp term
difference is absorbed below the accumulator's own ULP and the two kernels
agree bit-for-bit; with a==0 (the AZERO fixture, 0+x is exact) it survives to
the final bit and torch disagrees with itself across platforms — measured on
the Linux CI runner. The documented per-element order in pure IEEE float32
ops (sqrt/div/mul/add, each correctly rounded) is bit-identical on every IEEE
host and to the C implementation by construction, so it — not torch — is the
addcdiv gold source; torch is downgraded to a <=1-float32-ulp tolerance
sanity check (mirrors the #327 CosineAnnealingLR discriminator's
boundary_tolerant precedent in generate_expected_lr_scheduler.py). lerp has
NO such replication: its contract IS torch's FMA-fused kernel (fmaf on the C
side); python 3.12 has no math.fma and a float64 emulation double-rounds. The
C-side gold test carries lerp parity.
"""
from __future__ import annotations

import argparse

import numpy as np
import torch


def f32(v: float) -> float:
    return float(np.float32(v))


def _format_float_literal(v: float) -> str:
    s = repr(v)
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit_float_array(name: str, values: torch.Tensor | np.ndarray) -> str:
    if isinstance(values, torch.Tensor):
        flat = values.detach().flatten().tolist()
    else:
        flat = np.asarray(values, dtype=np.float32).flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def make_inputs(n: int, seed: int) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    g = torch.Generator().manual_seed(seed)
    a = torch.randn(n, generator=g, dtype=torch.float32)
    b = torch.randn(n, generator=g, dtype=torch.float32)
    c = torch.randn(n, generator=g, dtype=torch.float32)
    v = torch.rand(n, generator=g, dtype=torch.float32) * 2.0  # nonneg incl. near-0
    return a, b, c, v


LERP_WEIGHT = f32(0.1)  # 1-beta1 for AdamW default beta1=0.9; |w| < 0.5 branch


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_pointwise_fused.py - DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_POINTWISE_FUSED_H\n#define ODT_EXPECTED_POINTWISE_FUSED_H\n",
        "#include <stdlib.h>\n\n",
    ]

    for n in (32, 64):
        a, b, c, v = make_inputs(n, seed=1000 + n)

        # --- lerp: expected = a.lerp_(b, w) (torch's FMA-fused kernel) ---
        exp_lerp = a.clone()
        exp_lerp.lerp_(b, LERP_WEIGHT)

        # NOTE (unused-const hygiene): emit ONLY what the C tests consume at
        # this task's stage — Task 2 appends the pf_c_* + addcmul arrays,
        # Task 3 the pf_v_* + addcdiv arrays. c/v are still GENERATED here so
        # the shared seed keeps every array bit-stable across tasks.
        parts.append(emit_float_array(f"pf_a_n{n}", a))
        parts.append(emit_float_array(f"pf_b_n{n}", b))
        parts.append(emit_float_array(f"pf_expected_lerp_n{n}", exp_lerp))
        parts.append("\n")

        # --- addcmul: expected = a.addcmul_(b, c, value=s); torch vector path
        # is separate-rounded left-assoc base + (s*b)*c. Self-check replicates
        # exactly that with numpy float32 and asserts bit-equality.
        s_addcmul = f32(0.001)  # 1-beta2 for AdamW default beta2=0.999
        parts.append(emit_float_array(f"pf_c_n{n}", c))  # first consumed by addcmul tests
        exp_addcmul = a.clone()
        exp_addcmul.addcmul_(b, c, value=s_addcmul)
        np_a = a.numpy().astype(np.float32)
        np_rep = np_a + (np.float32(s_addcmul) * b.numpy()) * c.numpy()
        assert np.array_equal(np_rep.astype(np.float32), exp_addcmul.numpy()), (
            f"addcmul n={n}: torch kernel is not separate-rounded left-assoc "
            "(FMA tail leak?) - fixture size must stay a multiple of 32"
        )
        parts.append(emit_float_array(f"pf_expected_addcmul_n{n}", exp_addcmul))

        # b == c aliasing fixture (AdamW K2 uses addcmul(v, g, g)):
        exp_addcmul_bb = a.clone()
        exp_addcmul_bb.addcmul_(b, b, value=s_addcmul)
        parts.append(emit_float_array(f"pf_expected_addcmul_bb_n{n}", exp_addcmul_bb))

        # a == 0 fixture: AdamW's FIRST second-moment step (v starts at zero) —
        # the addcmul term IS the result (0 + x is exact), so the product's
        # reassociation bits fully survive to the gold comparison. This kills
        # the grouping-mutation blind spot of the O(1)-a fixtures, where the
        # s~1e-3 term sits below a[i]'s ULP and absorption hides the mutation.
        exp_addcmul_azero = torch.zeros(n).addcmul_(b, c, value=s_addcmul)
        np_rep_azero = np.float32(0.0) + (np.float32(s_addcmul) * b.numpy()) * c.numpy()
        assert np.array_equal(np_rep_azero.astype(np.float32), exp_addcmul_azero.numpy()), (
            f"addcmul azero n={n}: torch kernel is not separate-rounded left-assoc "
            "(FMA tail leak?) - fixture size must stay a multiple of 32"
        )
        parts.append(emit_float_array(f"pf_expected_addcmul_azero_n{n}", exp_addcmul_azero))

        # --- addcdivDenom: torch route = denom tensor then addcdiv_ (adam.py
        # L545-547); numpy replicates the six separate roundings denom-free.
        #
        # GOLD SOURCE (#353): torch's addcdiv vectorization is
        # platform-dependent — Linux-AVX2 fuses the final multiply-add
        # (measured via the azero self-check below going from bit-equal on
        # macOS-ARM to <=1-ulp-off on Linux), so torch CANNOT be the
        # cross-platform gold source for addcdiv. The numpy replication
        # below — pure IEEE float32 sqrt/div/mul/add, each correctly rounded,
        # in the documented order — IS the gold: bit-identical on every IEEE
        # host and to the C implementation by construction. Torch is kept
        # only as a <=1-float32-ulp tolerance sanity check (mirrors the #327
        # CosineAnnealingLR discriminator's boundary_tolerant precedent).
        s_addcdiv = f32(-0.004)  # -(lr/bc1)-shaped
        d_scale = f32(0.0316227766016838)  # sqrt(1-beta2**1), t=1-shaped
        eps = f32(1e-8)
        parts.append(emit_float_array(f"pf_v_n{n}", v))  # first consumed by addcdiv tests
        denom = (v.sqrt() / d_scale).add_(eps)
        exp_addcdiv = a.clone()
        exp_addcdiv.addcdiv_(b, denom, value=s_addcdiv)
        np_d = np.sqrt(v.numpy().astype(np.float32))
        np_d = np_d / np.float32(d_scale)
        np_d = np_d + np.float32(eps)
        np_n = np.float32(s_addcdiv) * b.numpy()
        np_rep = (a.numpy().astype(np.float32) + np_n / np_d).astype(np.float32)
        t_addcdiv = exp_addcdiv.numpy()
        diff = np.abs(t_addcdiv - np_rep)
        ulp = np.spacing(np.maximum(np.abs(t_addcdiv), np.abs(np_rep)).astype(np.float32))
        assert (diff <= ulp).all(), (
            f"addcdivDenom n={n}: torch result more than 1 float32 ulp from "
            "the documented numpy order - platform-fusion divergence beyond "
            "the known Linux-AVX2 case (#353)"
        )
        parts.append(emit_float_array(f"pf_expected_addcdiv_n{n}", np_rep))

        # a == 0 fixture: mutation-sensitivity check (Task 2 lesson applied
        # proactively) showed the O(1)-a gold above is grouping-mutation BLIND
        # here — quotient = (s*b)/d sits ~3-4 orders of magnitude below a's
        # ULP-relevant scale (d averages in the tens), so s*(b/d) vs (s*b)/d
        # never flips a single final bit after a+quotient (measured: 0/32,
        # 0/64 elements differ). With a=0 the addition is exact (0+x==x) and
        # the quotient's own rounding bits survive to the gold comparison
        # (measured: 17/32, 21/64 elements now differ under the mutation).
        # This is also the exact fixture where the Linux-AVX2 fusion surfaces
        # (#353): with a==0 the fused term's <=1-ulp difference from the
        # separate-rounded macOS-ARM kernel is no longer absorbed below an
        # O(1) accumulator's ULP, so torch's own result becomes
        # platform-dependent — the numpy replication is the only viable gold.
        exp_addcdiv_azero = torch.zeros(n).addcdiv_(b, denom, value=s_addcdiv)
        np_rep_azero = (np.float32(0.0) + np_n / np_d).astype(np.float32)
        t_azero = exp_addcdiv_azero.numpy()
        diff_azero = np.abs(t_azero - np_rep_azero)
        ulp_azero = np.spacing(
            np.maximum(np.abs(t_azero), np.abs(np_rep_azero)).astype(np.float32)
        )
        assert (diff_azero <= ulp_azero).all(), (
            f"addcdivDenom azero n={n}: torch result more than 1 float32 ulp "
            "from the documented numpy order - platform-fusion divergence "
            "beyond the known Linux-AVX2 case (#353)"
        )
        parts.append(emit_float_array(f"pf_expected_addcdiv_azero_n{n}", np_rep_azero))

    parts.append(
        f"static const float pf_lerp_weight = {_format_float_literal(LERP_WEIGHT)};\n"
    )
    parts.append(f"static const float pf_addcmul_s = {_format_float_literal(f32(0.001))};\n")
    parts.append(f"static const float pf_addcdiv_s = {_format_float_literal(f32(-0.004))};\n")
    parts.append(
        f"static const float pf_addcdiv_dscale = "
        f"{_format_float_literal(f32(0.0316227766016838))};\n"
    )
    parts.append(f"static const float pf_addcdiv_eps = {_format_float_literal(f32(1e-8))};\n")
    parts.append("#endif // ODT_EXPECTED_POINTWISE_FUSED_H\n")
    with open(args.out, "w") as f:
        f.write("".join(parts))


if __name__ == "__main__":
    main()
