#define SOURCE_FILE "ROUNDING"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "Common.h"
#include "RNG.h"
#include "Rounding.h"

/**
 * Rounds a floating-point value to the nearest integer using half-to-even rule.
 * When the fractional part is EXACTLY 0.5, the result is rounded to the nearest even integer.
 *
 * @return The rounded integer value.
 */
// C round(): rounds half away from zero (C17 7.12.9.6)
int32_t roundHalfAway(float input) {
    return round(input);
}


/**
 * Returns a random floating-point number generated by the Random Number Generator.
 *
 * The value is uniformly distributed in the range [0.0, 1.0).
 *
 * @return A pseudo-random float in the range [0.0, 1.0).
 */
float randfloat() {
    return rngNextFloat();
}
/**
 * Performs stochastic rounding with half-to-even behavior.
 * Adds a random offset in [-0.5, 0.5) before applying roundHalfAway().
 *
 * @return The stochastically rounded integer value.
 */
int32_t roundSRHalfAway(const float input) {
    return roundHalfAway(input + randfloat() - 0.5f);
}

int32_t roundByMode(const float input, const roundingMode_t roundingMode) {
    switch (roundingMode) {
    case HALF_AWAY:
        return roundHalfAway(input);
    case SR_HALF_AWAY:
        return roundSRHalfAway(input);
    }
    return 0;
}

int32_t rescaleIntoAccumulatorScale(int32_t paramQ, float paramScale, float accumulatorScale,
                                    roundingMode_t roundingMode) {
    float rescaled = (float)paramQ * paramScale / accumulatorScale;
#ifdef ODT_SEED_GUARD
    /* !(x <= T), NOT (x > T): also catches NaN (0*inf when accumulatorScale
     * underflows to 0). Reserve the real worst int16 product 32768*32767
     * (the -32768 case), not qMax*qMax. */
    if (!(fabsf(rescaled) <= 2147483647.0f - 32768.0f * 32767.0f)) {
        PRINT_ERROR("rescaleIntoAccumulatorScale: param scale incompatible with accumulator "
                    "scale — seed overflows int32 (#189)");
        exit(1);
    }
#endif
    return roundByMode(rescaled, roundingMode);
}

float clamp(float input, float min, float max) {
    if (input < min) {
        return min;
    }
    if (input > max) {
        return max;
    }
    return input;
}

int32_t saturatingSubstraction(int32_t minuend, int32_t subtrahend, int32_t min, int32_t max)
{
    if (subtrahend > 0) {
        if (minuend < min + subtrahend) {
            return min;
        }
    } else {
        if (minuend > max + subtrahend) {
            return max;
        }
    }
    int32_t difference = minuend - subtrahend;
    return difference;
}
