#!/usr/bin/env python3
"""Generate expected_adaptive_avg_pool_1d.h for UnitTestAdaptiveAvgPool1d.

PyTorch torch.nn.functional.adaptive_avg_pool1d ground truth: forward output and
propLoss (dL/dx). Overlap/upsample fixtures use torch.randn_like(y) lossGrad (and
emit it as a gold array) so backward-path positional mutations are non-vacuous
(per codebase_uniform_lossgrad_mutation_vacuity). Divisor is the actual window
size; adaptive pooling has no padding.

Run via `uv run` (CMake wires this automatically).
"""
import argparse
import sys
from pathlib import Path

import torch
import torch.nn.functional as F


def _format_float_literal(v: float) -> str:
    s = repr(v)
    if s in ("inf", "-inf", "nan"):
        raise ValueError(f"non-finite gold value: {v!r}")
    return s + "f"


def emit_float_array(name: str, tensor: torch.Tensor) -> str:
    flat = tensor.detach().flatten().tolist()
    body = ", ".join(_format_float_literal(v) for v in flat)
    return (
        f"static const float {name}[] = {{ {body} }};\n"
        f"static const size_t {name}_len = {len(flat)};\n"
    )


def _hand_adaptive_forward(x, output_size):
    """floor/ceil reference (spec §2): start=floor(o*L/Lout), end=ceil((o+1)*L/Lout)."""
    B, C, L = x.shape
    out = torch.zeros((B, C, output_size))
    for b in range(B):
        for c in range(C):
            for o in range(output_size):
                start = (o * L) // output_size
                end = ((o + 1) * L + output_size - 1) // output_size
                out[b, c, o] = x[b, c, start:end].sum() / (end - start)
    return out


def _run_fixture(name, x, *, output_size, loss_grad_kind="ones", loss_seed=None):
    x_in = x.clone().detach().requires_grad_(True)
    y = F.adaptive_avg_pool1d(x_in, output_size)

    expected_y = _hand_adaptive_forward(x_in.detach(), output_size)
    assert torch.allclose(y.detach(), expected_y, atol=1e-5), (
        f"{name}: adaptive_avg_pool1d forward disagrees with hand-derived reference"
    )

    if loss_grad_kind == "ones":
        gy = torch.ones_like(y)
    elif loss_grad_kind == "randn":
        # Explicit literal seed (not hash(name), which is non-reproducible across
        # runs under PYTHONHASHSEED randomization) so the backward gold is stable
        # every regeneration — Task 3's backward tests depend on these arrays.
        if loss_seed is None:
            raise ValueError(f"{name}: randn lossGrad requires an explicit loss_seed")
        torch.manual_seed(loss_seed)
        gy = torch.randn_like(y)
    else:
        raise ValueError(loss_grad_kind)

    y.backward(gy)
    return {
        "name": name,
        "x": x_in.detach(),
        "y": y.detach(),
        "dx": x_in.grad.detach(),
        "gy": gy.detach(),
        "loss_grad_kind": loss_grad_kind,
    }


def fixture_basic():
    x = torch.tensor([[[1.0, 2.0, 3.0, 4.0]]])
    return _run_fixture("basic", x, output_size=2)


def fixture_multi_channel():
    torch.manual_seed(301)
    x = torch.randn(1, 3, 5)
    return _run_fixture("multiChannel", x, output_size=2, loss_grad_kind="randn", loss_seed=401)


def fixture_multi_batch():
    torch.manual_seed(302)
    x = torch.randn(4, 2, 6)
    return _run_fixture("multiBatch", x, output_size=4, loss_grad_kind="randn", loss_seed=402)


def fixture_global():
    torch.manual_seed(303)
    x = torch.randn(1, 2, 7)
    return _run_fixture("global", x, output_size=1)


def fixture_identity():
    x = torch.tensor([[[1.0, 2.0, 3.0, 4.0]]])
    return _run_fixture("identity", x, output_size=4)


def fixture_upsample():
    torch.manual_seed(305)
    x = torch.randn(1, 1, 3)
    return _run_fixture("upsample", x, output_size=5, loss_grad_kind="randn", loss_seed=403)


def emit_fixture(parts, fx):
    pre = f"adaptiveAvgPool1d_{fx['name']}"
    parts.append(emit_float_array(f"input_{pre}", fx["x"]))
    parts.append(emit_float_array(f"expectedForward_{pre}", fx["y"]))
    parts.append(emit_float_array(f"expectedPropLoss_{pre}", fx["dx"]))
    if fx["loss_grad_kind"] != "ones":
        parts.append(emit_float_array(f"lossGrad_{pre}", fx["gy"]))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    parts = [
        "// AUTOGENERATED by generate_expected_adaptive_avg_pool_1d.py — DO NOT EDIT\n",
        "#ifndef ODT_EXPECTED_ADAPTIVE_AVG_POOL_1D_H\n",
        "#define ODT_EXPECTED_ADAPTIVE_AVG_POOL_1D_H\n",
        "#include <stdlib.h>\n\n",
    ]
    for fx in [
        fixture_basic(),
        fixture_multi_channel(),
        fixture_multi_batch(),
        fixture_global(),
        fixture_identity(),
        fixture_upsample(),
    ]:
        emit_fixture(parts, fx)
    parts.append("\n#endif // ODT_EXPECTED_ADAPTIVE_AVG_POOL_1D_H\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
